NinetyNinecats/config/routes.rb
NinetyNinecats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new, :update] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resource :user
  resource :session

  root to: "cats#index"
end

NinetyNinecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string(255)      not null
#  name        :string(255)      not null
#  sex         :string(255)      not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Cat < ActiveRecord::Base
  belongs_to :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id

  has_many :rental_requests,
    class_name: 'CatRentalRequest',
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy

  validates :birth_date, :color, :name, :sex, presence: true

end

NinetyNinecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    if owns_cat?
      render :edit
    else
      flash[:errors] = "You don't own #{@cat.name}!"
      redirect_to cats_url
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.persisted?
      redirect_to cat_url(@cat)
    else
      render :edit
    end

  end

  def destroy
    @cat = Cat.find(params[:id])

    if @cat.persisted?
      @cat.destroy
      redirect_to cats_url
    else
      raise "No such cat exists"
    end
  end


  private
  def owns_cat?
    current_user.id == @cat.user_id
  end

  def cat_params
    params.require(:cat).permit(:name, :birth_date,
      :color, :sex, :description)
  end
end

NinetyNinecats/app/views/cats/_form.html.erb
<input
  type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">



<label for-"cat_name">Name</label>
<input type="text" name="cat[name]" value="<%=@cat.name%>">
<br><br>

<label for-"cat_sex">Sex</label><br>
<input type="radio" name="cat[sex]" id="cat_sex_female"
  value="F" <%= (@cat.sex == "F") ? "checked" : "" %>>
<label for-"cat_sex_female">Female</label><br>
<input type="radio" name="cat[sex]" id="cat_sex_male"
  value="M" <%= (@cat.sex == "M") ? "checked" : "" %>>
<label for-"cat_sex_male">Male</label><br><br>

<label for-"cat_color">Color</label>
<select name="cat[color]" id="cat_color">
  <option value=""></option>
  <option value="brown"
    <%= (@cat.color == "brown") ? "selected" : "" %>>Brown</option>
  <option value="black"
    <%= (@cat.color == "black") ? "selected" : "" %>>Black</option>
  <option value="white"
    <%= (@cat.color == "white") ? "selected" : "" %>>White</option>
</select><br><br>

<label for-"cat_birth_date">Birthday</label>
<time>
  <input type="date" name="cat[birth_date]"
    value="<%=@cat.birth_date%>">
</time><br><br>

<label for-"cat_description">Description</label><br>

  <textarea name="cat[description]" cols="30" rows="10">
    <%= @cat.description %></textarea>
<br><br>

NinetyNinecats/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<form action="<%= cat_url(@cat) %>" method="post">
    <input type="hidden" name="_method" value="patch">

      <%= render "cats/form" %>

    <button>Update Cat</button>
</form>

NinetyNinecats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<form action="<%= new_cat_url %>" method="get">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <button>Create Cat</button>
</form>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>

    <form action="<%= cat_url(cat) %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

        <button>Delete Cat</button>
    </form>

  <% end %>
</ul>

NinetyNinecats/app/views/cats/new.html.erb
<h1>Register Cat</h1>

<form action="<%= cats_url %>" method="post">
    <%= render "cats/form" %>

    <button>Create Cat</button>
</form>

NinetyNinecats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <th>Cattributes</th>
  <tr>
    <td>Owner</td>
    <td><%= @cat.owner.user_name %></td>
  </tr>
  <tr>
    <td>Color</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>Birthday</td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <td>Sex</td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

<h3>Description</h3>
<p><%= @cat.description %></p>
<br><br>


<form action="<%= new_cat_rental_request_url %>" method="get">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <button>Request Cat Rental</button>
</form>
<br><br>

  <table>
    <th>Rental Requests</th>
    <tr>
      <td>Start Date</td>
      <td>End Date</td>
      <td>Status</td>
      <td>Action</td>
      <td>Update</td>
    </tr>
    <% @cat.rental_requests.each do |request| %>
      <tr>
        <td><%= request.start_date %></td>
        <td><%= request.end_date %></td>
        <td><%= request.status %></td>
        <form action="<%= cat_rental_request_url %>" method="post">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">

              <input
                type="hidden"
                name="request_id"
                value="<%= request.id %>">

                <input
                  type="hidden"
                  name="requester_id"
                  value="<%= current_user.id %>">

                  <input
                    type="hidden"
                    name="cat_id"
                    value="<%= request.cat_id %>">

          <input type="hidden" name="_method" value="patch">
          <td>
            <select name="request[status]" id="cat_rental_request_status">
              <option value=""></option>
              <option value="Pending"
                <%= (request.status == "Pending") ? "selected" : "" %>>Pending</option>
              <option value="Approved"
                <%= (request.status == "Approved") ? "selected" : "" %>>Approved</option>
              <option value="Denied"
                <%= (request.status == "Denied") ? "selected" : "" %>>Denied</option>
            </select><br><br>

          </td>
          <td><button>Update</button></td>
        </form>
      </tr>
    <% end %>

  </table>