NinetyNinecats/config/routes.rb
NinetyNinecats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new, :update] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resource :user
  resource :session

  root to: "cats#index"
end

NinetyNinecats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string(255)      default("Pending"), not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  belongs_to :cat,
    class_name: 'Cat',
    foreign_key: :cat_id,
    primary_key: :id

  after_initialize do |cat_rental_request|
    cat_rental_request.status ||= "Pending"
  end

  validates :status, inclusion: { in: %w(Pending Approved Denied),
    message: "%{value} is not a valid status"}
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validate :no_approved_requests

  def approve!
    transaction do
      self.status = "Approved"
      self.save!
      overlapping_pending_requests.update_all(status: 'DENIED')
    end
  end

  def deny!
    self.status = "Denied"
    self.save!
  end

  def approved?
    self.status == "Approved"
  end

  def denied?
    self.status == "Denied"
  end

  def pending?
    self.status == "Pending"
  end

  # private
  def assign_pending_status
    self.status ||= "Pending"
  end

  def overlapping_requests
    overlap_cond = <<-SQL
      NOT ((:start_date > cat_rental_requests.end_date) OR
        (:end_date < cat_rental_requests.start_date)) AND
        cat_rental_requests.id != :id
      SQL

    CatRentalRequest.where(overlap_cond, :start_date => start_date,
      :end_date => end_date, :id => id).where(cat_id: cat_id)
  end

  def overlapping_approved_requests
    approve_cond = <<-SQL
        status = "Approved"
    SQL
    overlapping_requests.where(approve_cond)
  end

  def no_approved_requests
    unless overlapping_approved_requests.empty?
      errors.add(:approval_status, "There is already an approved request!")
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'Pending'")
  end

  def does_not_overlap_approved_request
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        "Request conflicts with existing approved request"
    end
  end

  def start_must_come_before_end
    return if start_date < end_date
    errors[:start_date] << "must come before end date"
    errors[:end_date] << "must come after start date"
  end

end

NinetyNinecats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cat_rental_request = CatRentalRequest.new

    render :new
  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :show
  end

  def create

    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    @cat_rental_request.user_id = current_user.id

    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat_id)
    else
      render :new
    end
  end

  def update
    @cat_rental_request = CatRentalRequest.find(params[:request_id])
    @cat_rental_request.status = params[:request][:status]

    
    if Cat.find(params[:cat_id]).owner.id != params[:requester_id].to_i
        flash[:errors] = "You don't own #{Cat.find(params[:cat_id]).name}!"
        redirect_to cat_url(@cat_rental_request.cat_id)
    else
      if @cat_rental_request.save
        redirect_to cat_url(@cat_rental_request.cat_id)
      else
        flash[:errors] = "Update did not work!"
        redirect_to cat_url(@cat_rental_request.cat_id)
      end
    end

  end

  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  private
  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:start_date, :end_date, :cat_id)
  end

end

NinetyNinecats/app/views/cat_rental_requests/new.html.erb
<h1>Request-A-Cat</h1>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
  <label for-"cat_rental_request_name">Name</label>
  <select name="cat_rental_request[cat_id]" id="cat_rental_request_cat_id">
    <option value=""></option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>"
        <%= (@cat_rental_request.cat_id == cat.id) ? "selected" : "" %>><%= cat.name %></option>
    <% end %>
  </select><br><br>

  <label for-"cat_rental_request_start_date">Start Date</label>
  <time>
    <input type="date" name="cat_rental_request[start_date]"
      value="<%= @cat_rental_request.start_date %>">
  </time><br><br>

  <label for-"cat_rental_request_end_date">End Date</label>
  <time>
    <input type="date" name="cat_rental_request[end_date]"
      value="<%= @cat_rental_request.end_date %>">
  </time><br><br>

    <button>Submit Request for Cat</button>
</form>

NinetyNinecats/app/views/cat_rental_requests/show.html.erb
<h1>Your request has been submitted</h1>